library(testthat)

# Tests for R/fia_data.R (Phase 1 FIA data layer). These run against the bundled
# synthetic fixture inst/extdata/FIADB_demo.db (STATECD 53 / Washington, two
# EXPVOL/EXPCURR/EXPGROW evaluations: 531901 = 2019 and 532101 = 2021, the 2021
# plots being remeasurements of the 2019 plots). The fixture is generated by
# _dev/make_fia_demo_db.R.

demo_db <- function() {
  p <- system.file("extdata", "FIADB_demo.db", package = "RForInvt")
  if (!nzchar(p) || !file.exists(p)) p <- file.path("..", "..", "inst", "extdata", "FIADB_demo.db")
  p
}

skip_if_no_demo <- function() {
  p <- demo_db()
  if (!nzchar(p) || !file.exists(p)) skip("FIADB_demo.db fixture not available")
  testthat::skip_if_not_installed("RSQLite")
  testthat::skip_if_not_installed("sqldf")
  p
}

# load tables once into an in-memory list for the list-source equivalence tests
load_tables <- function(p) {
  con <- DBI::dbConnect(RSQLite::SQLite(), p)
  on.exit(DBI::dbDisconnect(con))
  tabs <- list()
  for (t in c("PLOT", "COND", "TREE", "POP_EVAL", "POP_EVAL_TYP",
              "POP_STRATUM", "POP_PLOT_STRATUM_ASSGN")) {
    tabs[[t]] <- DBI::dbGetQuery(con, paste("select * from", t))
  }
  tabs
}

# ---- fia_db ----------------------------------------------------------------

test_that("fia_db wraps a path, a connection, and a table list", {
  p <- skip_if_no_demo()

  h_path <- fia_db(p)
  expect_s3_class(h_path, "fia_db")
  expect_equal(h_path$kind, "sqlite")

  con <- DBI::dbConnect(RSQLite::SQLite(), p)
  on.exit(DBI::dbDisconnect(con))
  h_con <- fia_db(con = con)
  expect_equal(h_con$kind, "con")

  h_list <- fia_db(tables = load_tables(p))
  expect_equal(h_list$kind, "list")

  expect_error(fia_db(), "path.*con.*tables")
  expect_output(print(h_path), "fia_db")
})

# ---- fia_evalid ------------------------------------------------------------

test_that("fia_evalid finds evaluations, honors aliases and most_recent", {
  p <- skip_if_no_demo()
  db <- fia_db(p)

  ev_all <- fia_evalid(db, statecd = 53, eval_type = "EXPVOL")
  expect_s3_class(ev_all, "data.frame")
  expect_setequal(ev_all$EVALID, c(531901, 532101))
  expect_true(all(ev_all$EVAL_TYP == "EXPVOL"))

  # alias "vol" resolves to EXPVOL; most_recent keeps the 2021 eval only
  ev_mr <- fia_evalid(db, statecd = 53, eval_type = "vol", most_recent = TRUE)
  expect_equal(nrow(ev_mr), 1L)
  expect_equal(ev_mr$EVALID, 532101)
  expect_equal(ev_mr$END_INVYR, 2021)

  # year filter
  ev_19 <- fia_evalid(db, statecd = 53, eval_type = "EXPVOL", years = 2019)
  expect_equal(ev_19$EVALID, 531901)

  # statecd filter excludes everything for a wrong state
  expect_equal(nrow(fia_evalid(db, statecd = 99, eval_type = "EXPVOL")), 0L)
})

# ---- fia_plots -------------------------------------------------------------

test_that("fia_plots returns condition rows with full design columns", {
  p <- skip_if_no_demo()
  db <- fia_db(p)
  ev <- fia_evalid(db, statecd = 53, eval_type = "EXPVOL", most_recent = TRUE)

  pl <- fia_plots(db, evalid = ev)
  expect_s3_class(pl, "data.frame")

  # one row per PLT_CN x CONDID
  expect_false(any(duplicated(pl[, c("PLT_CN", "CONDID")])))

  # required design columns present and populated
  need <- c("EVALID", "PLT_CN", "CONDID", "COND_STATUS_CD", "CONDPROP_UNADJ",
            "EXPNS", "ADJ_FACTOR_SUBP", "ADJ_FACTOR_MICR", "ESTN_UNIT",
            "STRATUM_CN", "COUNTYCD")
  expect_true(all(need %in% names(pl)))
  expect_false(any(is.na(pl$EXPNS)))
  expect_false(any(is.na(pl$CONDPROP_UNADJ)))

  # nonforest conditions are retained (needed for area + zero-fill)
  expect_true(any(pl$COND_STATUS_CD == 2))

  # accepts an integer EVALID directly and matches the data.frame form
  pl_int <- fia_plots(db, evalid = 532101)
  expect_equal(nrow(pl_int), nrow(pl))

  # cond_filter narrows to forested conditions only
  pl_f <- fia_plots(db, evalid = 532101, cond_filter = "COND_STATUS_CD == 1")
  expect_true(all(pl_f$COND_STATUS_CD == 1))
  expect_lt(nrow(pl_f), nrow(pl))
})

# ---- fia_trees -------------------------------------------------------------

test_that("fia_trees computes TPA_EXP from the right adjustment factor", {
  p <- skip_if_no_demo()
  db <- fia_db(p)
  ev <- fia_evalid(db, statecd = 53, eval_type = "EXPVOL", most_recent = TRUE)

  tr <- fia_trees(db, evalid = ev)
  expect_s3_class(tr, "data.frame")
  expect_true(all(c("TPA_UNADJ", "ADJ_FACTOR", "TPA_EXP", "SPCD", "DIA",
                    "TRE_CN", "PLT_CN") %in% names(tr)))

  # TPA_EXP is exactly TPA_UNADJ * ADJ_FACTOR
  expect_equal(tr$TPA_EXP, tr$TPA_UNADJ * tr$ADJ_FACTOR)

  # microplot trees (DIA < 5) take the MICR factor; larger trees take SUBP
  micr <- tr$DIA < 5
  expect_true(all(tr$ADJ_FACTOR[micr]  %in% c(1.10, 1.18)))
  expect_true(all(tr$ADJ_FACTOR[!micr] %in% c(1.02, 1.05)))

  # default filter keeps only live trees
  expect_true(all(tr$STATUSCD == 1) || !"STATUSCD" %in% names(tr))
})

test_that("fia_trees spans multiple evaluations when given several EVALIDs", {
  p <- skip_if_no_demo()
  db <- fia_db(p)
  ev2 <- fia_evalid(db, statecd = 53, eval_type = "EXPVOL")  # both years

  tr2 <- fia_trees(db, evalid = ev2)
  expect_setequal(unique(tr2$INVYR), c(2019, 2021))
  expect_setequal(unique(tr2$EVALID), c(531901, 532101))
})

# ---- source equivalence ----------------------------------------------------

test_that("SQLite path and in-memory table list give identical frames", {
  p <- skip_if_no_demo()
  db_sql <- fia_db(p)
  db_lst <- fia_db(tables = load_tables(p))

  pl_sql <- fia_plots(db_sql, evalid = 532101)
  pl_lst <- fia_plots(db_lst, evalid = 532101)
  expect_equal(nrow(pl_sql), nrow(pl_lst))
  expect_equal(sort(pl_sql$PLT_CN), sort(pl_lst$PLT_CN))

  tr_sql <- fia_trees(db_sql, evalid = 532101)
  tr_lst <- fia_trees(db_lst, evalid = 532101)
  expect_equal(nrow(tr_sql), nrow(tr_lst))
  expect_equal(sum(tr_sql$TPA_EXP), sum(tr_lst$TPA_EXP), tolerance = 1e-9)
})
